export enum Status {
  SCHEDULED = 'SCHEDULED',
  PPT_DONE = 'PPT_DONE',
  POLL_FREEZED = 'POLL_FREEZED',
  TEST_COMPLETED = 'TEST_COMPLETED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  RECRUITMENT_PROCESS_COMPLELETED = 'RECRUITMENT_PROCESS_COMPLELETED',
  OFFER_LETTER_RELEASED = 'OFFER_LETTER_RELEASED',
  PROCESS_ON_HOLD = 'PROCESS_ON_HOLD',
  PROCESS_TERMINATED = 'PROCESS_TERMINATED',
  OFFER_REVOKED = 'OFFER_REVOKED',
}
