export enum EventStatus {
  INITIALIZED = "INITIALIZED",
  SCHEDULED = "SCHEDULED",
  IN_PROCESS = "IN_PROCESS",
  COMPLETED = "COMPLETED",
  ON_HOLD = "ON_HOLD",
  CANCELED = "CANCELED",
  RESCHEDULED = "RESCHEDULED",
}
