export enum OfferStatusEnum {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  ONGOING = "ONGOING",
  PPO_ACCEPTED = "PPO_ACCEPTED",
  PLACEMENT_FTE = "PLACEMENT_FTE",
  PLACEMENT_PPO = "PLACEMENT_PPO",
}
