export const SEQUELIZE_DAO = "SEQUELIZE",
  USER_DAO = "USER_DAO",
  STUDENT_DAO = "STUDENT_DAO",
  TPC_MEMBER_DAO = "TPC_MEMBER_DAO",
  FACULTY_DAO = "FACULTY_DAO",
  FACULTY_APPROVAL_REQUEST_DAO = "FACULTY_APPROVAL_REQUEST_DAO",
  RECRUITER_DAO = "RECRUITER_DAO",
  SEASON_DAO = "SEASON_DAO",
  COMPANY_DAO = "COMPANY_DAO",
  JOB_DAO = "JOB_DAO",
  JOB_COORDINATOR_DAO = "JOB_COORDINATOR_DAO",
  JOB_STATUS_DAO = "JOB_STATUS_DAO",
  SALARY_DAO = "SALARY_DAO",
  PROGRAM_DAO = "PROGRAM_DAO",
  EVENT_DAO = "EVENT_DAO",
  RESUME_DAO = "RESUME_DAO",
  APPLICATION_DAO = "APPLICATION_DAO",
  PENALTY_DAO = "PENALTY_DAO",
  ON_CAMPUS_OFFER_DAO = "ON_CAMPUS_OFFER_DAO",
  OFF_CAMPUS_OFFER_DAO = "OFF_CAMPUS_OFFER_DAO";

export const AUTH_SERVICE = "AUTH_SERVICE",
  TPC_MEMBER_SERVICE = "TPC_MEMBER_SERVICE",
  PROGRAM_SERVICE = "PROGRAM_SERVICE",
  USER_SERVICE = "USER_SERVICE",
  STUDENT_SERVICE = "STUDENT_SERVICE",
  EVENT_SERVICE = "EVENT_SERVICE",
  RECRUITER_SERVICE = "RECRUITER_SERVICE",
  SEASON_SERVICE = "SEASON_SERVICE",
  COMPANY_SERVICE = "COMPANY_SERVICE",
  JOB_SERVICE = "JOB_SERVICE",
  JOB_STATUS_SERVICE = "JOB_STATUS_SERVICE",
  PENALTY_SERVICE = "PENALTY_SERVICE",
  JOB_COORDINATOR_SERVICE = "JOB_COORDINATOR_SERVICE",
  FACULTY_SERVICE = "FACULTY_SERVICE";

export enum COURSES {
  BTECH = "BTECH",
  MTECH = "MTECH",
  MSC = "MSC",
  MS_RESEARCH = "MS_RESEARCH",
  PHD = "PHD",
}
export enum BRANCHES {
  MECHANICAL = "MECHANICAL",
  ELECTRICAL = "ELECTRICAL",
  CIVIL = "CIVIL",
  COMPUTER_SCIENCE = "COMPUTER_SCIENCE",
  METALLURGICAL = "METALLURGICAL",

  SPACE_ENG = "SPACE_ENG",
  COMMUNICATION_SIGNAL = "COMMUNICATION_SIGNAL",
  VLSI_DESIGN = "VLSI_DESIGN",
  ELECTRIC_VEHICLE = "ELECTRIC_VEHICLE",
  ADVANCED_MANUFACTURING = "ADVANCED_MANUFACTURING",
  MECHANICAL_SYSTEM_DESIGN = "MECHANICAL_SYSTEM_DESIGN",
  THERMAL_ENERGY_SYSTEM = "THERMAL_ENERGY_SYSTEM",
  MATERIAL_SCIENCE = "MATERIAL_SCIENCE",
  METALLURGICAL_ENG = "METALLURGICAL_ENG",

  ASTRONOMY = "ASTRONOMY",
  BIOTECHNOLOGY = "BIOTECHNOLOGY",
  CHEMISTRY = "CHEMISTRY",
  MATHEMATICS = "MATHEMATICS",
  PHYSICS = "PHYSICS",

  SPACE_SCIENCE = "SPACE_SCIENCE",
  HSS = "HSS",

  BIOSCIENCES = "BIOSCIENCES",
}

export const COURSE_BRANCH_MAP = {
  [COURSES.BTECH]: [BRANCHES.MECHANICAL, BRANCHES.ELECTRICAL],

  [COURSES.MTECH]: [BRANCHES.SPACE_ENG, BRANCHES.COMMUNICATION_SIGNAL, BRANCHES.VLSI_DESIGN, BRANCHES.ELECTRIC_VEHICLE,
  BRANCHES.ADVANCED_MANUFACTURING, BRANCHES.MECHANICAL_SYSTEM_DESIGN, BRANCHES.THERMAL_ENERGY_SYSTEM, BRANCHES.MATERIAL_SCIENCE,
  BRANCHES.METALLURGICAL_ENG],

  [COURSES.MSC]: [BRANCHES.ASTRONOMY, BRANCHES.BIOTECHNOLOGY, BRANCHES.CHEMISTRY, BRANCHES.MATHEMATICS, BRANCHES.PHYSICS],

  [COURSES.MS_RESEARCH]: [BRANCHES.SPACE_SCIENCE, BRANCHES.COMPUTER_SCIENCE, BRANCHES.ELECTRICAL, BRANCHES.HSS, BRANCHES.MECHANICAL],

  [COURSES.PHD]: [BRANCHES.ASTRONOMY, BRANCHES.BIOSCIENCES, BRANCHES.CHEMISTRY, BRANCHES.CIVIL, BRANCHES.COMPUTER_SCIENCE,
  BRANCHES.ELECTRICAL, BRANCHES.HSS, BRANCHES.MATHEMATICS, BRANCHES.MECHANICAL, BRANCHES.METALLURGICAL, BRANCHES.PHYSICS]
};
export const YEARS = ["2023", "2024", "2025"];
