export const SEQUELIZE_DAO = "SEQUELIZE",
  USER_DAO = "USER_DAO",
  STUDENT_DAO = "STUDENT_DAO",
  TPC_MEMBER_DAO = "TPC_MEMBER_DAO",
  FACULTY_DAO = "FACULTY_DAO",
  FACULTY_APPROVAL_REQUEST_DAO = "FACULTY_APPROVAL_REQUEST_DAO",
  RECRUITER_DAO = "RECRUITER_DAO",
  SEASON_DAO = "SEASON_DAO",
  COMPANY_DAO = "COMPANY_DAO",
  JOB_DAO = "JOB_DAO",
  JOB_COORDINATOR_DAO = "JOB_COORDINATOR_DAO",
  JOB_STATUS_DAO = "JOB_STATUS_DAO",
  SALARY_DAO = "SALARY_DAO",
  PROGRAM_DAO = "PROGRAM_DAO",
  EVENT_DAO = "EVENT_DAO",
  RESUME_DAO = "RESUME_DAO",
  APPLICATION_DAO = "APPLICATION_DAO",
  PENALTY_DAO = "PENALTY_DAO",
  ON_CAMPUS_OFFER_DAO = "ON_CAMPUS_OFFER_DAO",
  OFF_CAMPUS_OFFER_DAO = "OFF_CAMPUS_OFFER_DAO";

export const AUTH_SERVICE = "AUTH_SERVICE",
  TPC_MEMBER_SERVICE = "TPC_MEMBER_SERVICE",
  PROGRAM_SERVICE = "PROGRAM_SERVICE",
  USER_SERVICE = "USER_SERVICE",
  STUDENT_SERVICE = "STUDENT_SERVICE",
  EVENT_SERVICE = "EVENT_SERVICE",
  RECRUITER_SERVICE = "RECRUITER_SERVICE",
  SEASON_SERVICE = "SEASON_SERVICE",
  COMPANY_SERVICE = "COMPANY_SERVICE",
  JOB_SERVICE = "JOB_SERVICE",
  JOB_STATUS_SERVICE = "JOB_STATUS_SERVICE";

export enum COURSES {
  BTECH = "BTECH",
  BSC = "BSC",
  MTECH = "MTECH",
  MSC = "MSC",
  PG = "PG",
}
export enum BRANCHES {
  MECHANICAL = "MECHANICAL",
  ELECTRICAL = "ELECTRICAL",
}

export const COURSE_BRANCH_MAP = {
  [COURSES.BTECH]: [BRANCHES.MECHANICAL, BRANCHES.ELECTRICAL],
  [COURSES.PG]: [BRANCHES.ELECTRICAL, BRANCHES.MECHANICAL],
};
export const YEARS = ["2023", "2024", "2025"];
